<?php

return [
    'publishable_key' => env('STRIPE_KEY'),

    // https://dashboard.stripe.com/pricing-tables
    'pricing_table_id' => env('STRIPE_PRICING_TABLE_ID'),

    // https://dashboard.stripe.com/products
    'plans' => [
        'privacy_credit_monitoring' => [
            'product_id' => env('STRIPE_PLAN_PRIVACY_CREDIT_MONITORING'),
            'price_id' => env('STRIPE_PLAN_PRIVACY_CREDIT_MONITORING_PRICE'),
            'name' => 'Privacy Credit Monitoring',
            'array_products' => [
                'ppPIPMonitoringAndRemoval',
            ],
        ],
        'full_protection' => [
            'product_id' => env('STRIPE_PLAN_FULL_PROTECTION'),
            'price_id' => env('STRIPE_PLAN_FULL_PROTECTION_PRICE'),
            'name' => 'Full Protection',
            'array_products' => [
                'autoProductRefresh',
                'creditScoreCoach',
                'creditScoreDetails',
                'efx1bInstantMonitoring',
                'efx1bStandardMonitoring',
                'efx1bStandardMonitoringReportScorePMPM',
                'exp1bInstantMonitoring',
                'exp1bStandardMonitoring',
                'exp1bStandardMonitoringWithScoreTracker',
                'exp2bStandardMonitoring',
                'exp3bStandardMonitoring',
                'expNonTraditionalMonitoring',
                'expScoreSimulator',
                'idpAutoTitleMonitoring',
                'idpBundle1Insurance1mmRestoreBundleMonitoring',
                'idpBundle2Monitoring',
                'idpChangeOfAddressMonitoring',
                'idpCourtRecordsMonitoring',
                'idpDarkWebMonitoring',
                'idpDarkWebMonitoringV2',
                'idpFinancialThresholdMonitoring',
                'idpHomeTitleMonitoring',
                'idpInsurance1mmRestore',
                'idpInsurance1MRestore',
                'idpInsurance1MRestorePlusSpouse',
                'idpInsurance3MCashRecoveryPro',
                'idpInsurance3MCashRecoveryProPlusFamily',
                'idpInsurance3MCashRecoveryProPlusSpouse',
                'idpInsurance3MRestore',
                'idpInsurance3MRestorePlusSpouse',
                'idpInsurance5MCashRecoveryPro',
                'idpInsurance5MCashRecoveryProPlusFamily',
                'idpInsurance5MCashRecoveryProPlusSpouse',
                'idpNeighborhoodWatch',
                'idpSocialMediaMonitoring',
                'idpSSN10Monitoring',
                'idpSSNMonitoring',
                'idpSSNUnlimitedMonitoring',
                'idpSurfaceWebMonitoring',
                'idpTelecomSpoofingMonitoring',
                'mcmCreditProtection',
                'ppPIPMonitoringAndRemoval',
                'ppPIPMonitoringAndRemovalStandalone',
                'ppPIPScanOnly',
                'scoreTrackerAutoExp',
                'smTransactionSourcePlaid',
                'subscriptionManagerEnrichmentAndCancellation',
                'subscriptionManagerEnrichmentOnly',
                'tui1bCreditLock',
                'tui1bEnhancedMonitoring',
                'tui1bInstantEnhancedMonitoring',
                'tui1bInstantMonitoring',
                'tui1bScoreSimulator',
                'tui1bStandardMonitoring',
            ],
        ],
        
    ],
];
